@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

package designpatterns.observer {
    interface Observer {
        ~update(subject:Subject): void
    }
    abstract class Subject {
        -observers: Set<Observer>

        +attach(observer:Observer): void
        +detach(observer:Observer): void
        #notifyChange(): void
    }
}

package roborally {
    package controller {
        class AppController {}
        class GameController {}
    }

    package model {
        class Board {
            boardName
            gameID
            currentPlayer
            phase
            step
            stepMode
            moveCount
        }

        class Player {
            name
            color
            heading

            NO_REGISTERS
            NO_CARDS
        }

        class Space {
            x
            y
        }

        class Object {
        }

        class CommandCard {

        }

        class Command {
        }
    }

    package view {
    }


    class RoboRally {
    }



    RoboRally *-- "*" Board
    Board *--r "2..6" Player
    Board *-- "*" Space
    Space *-- "*" Object
    Player *-- "*" CommandCard
    CommandCard "1" -- "1" Command
    Player "1" -- "1" Space

}


@enduml