@startuml
'https://plantuml.com/use-case-diagram

actor :Players: as Players
rectangle Game {
    left to right direction

    usecase "Play the game" as Play
    usecase "Save the game" as save
    usecase "Load the game" as load
}

Players "2..6" -- Play
Players  -- save
Players  -- load

@enduml